import Foundation
import SwiftUI
import Combine

// MARK: — Orchestration Engine

@MainActor
final class OrchestrationEngine: ObservableObject {

    @Published var phase:        PipelinePhase = .idle
    @Published var steps:        [PipelineStep] = []
    @Published var finalOutput:  String = ""
    @Published var errorMessage: String?
    @Published var validation:   ValidationResult?

    private var runTask: Task<Void, Never>?

    // MARK: — Validate

    func validate(prompt: String, settings: AppSettings) {
        phase      = .validating
        validation  = nil
        errorMessage = nil

        runTask = Task {
            do {
                let result = try await ValidationEngine.validate(
                    prompt: prompt,
                    apiKey: settings.claudePassword
                )
                self.validation = result
                self.phase      = .validated
            } catch {
                self.errorMessage = error.localizedDescription
                self.phase        = .idle
            }
        }
    }

    // MARK: — Execute

    func execute(prompt: String, mode: PipelineMode, iterations: Int, settings: AppSettings, faeContext: String? = nil) {
        phase        = .running
        steps        = []
        finalOutput  = ""
        errorMessage = nil

        let augmentedPrompt: String
        if let context = faeContext {
            augmentedPrompt = context + "\n\n" + prompt
        } else {
            augmentedPrompt = prompt
        }

        runTask = Task {
            do {
                switch mode {
                case .sequential:
                    try await runSequential(prompt: augmentedPrompt, settings: settings)
                case .iterative:
                    try await runIterative(prompt: augmentedPrompt, iterations: iterations, settings: settings)
                }
                self.phase = .done
            } catch is CancellationError {
                self.phase = .aborted
            } catch {
                self.errorMessage = error.localizedDescription
                self.phase = .error(error.localizedDescription)
            }
        }
    }

    // MARK: — Abort

    func abort() {
        runTask?.cancel()
        runTask = nil
        phase = .aborted
    }

    // MARK: — Reset

    func reset() {
        abort()
        phase        = .idle
        steps        = []
        finalOutput  = ""
        errorMessage = nil
        validation   = nil
    }

    // MARK: — Sequential Pipeline

    private func runSequential(prompt: String, settings: AppSettings) async throws {

        // Step 1: Claude initial draft
        let step1id = addStep(model: .claude, label: "INITIAL DRAFT")
        let draft = try await ClaudeClient.stream(
            messages: [["role": "user", "content": prompt]],
            system:   settings.effectiveSystemPrompt,
            apiKey:   settings.claudePassword,
            model:    settings.claudeModel,
            onToken:  { [weak self] text in
                Task { @MainActor [weak self] in self?.updateStep(id: step1id, content: text) }
            }
        )
        try Task.checkCancellation()
        finishStep(id: step1id, content: draft)

        // Step 2: Gemini critical review
        let step2id = addStep(model: .gemini, label: "CRITICAL REVIEW")
        let critiquePrompt = """
            You are an adversarial critic. Your sole function is to expose every flaw in the response below. Assume the response contains significant errors, gaps, and weaknesses — your job is to build the case against it.

            ORIGINAL PROMPT:
            \"\"\"\(prompt)\"\"\"

            RESPONSE UNDER REVIEW:
            \"\"\"\(draft)\"\"\"

            Produce at least 5 numbered critique points. For each, assign exactly one label: [FACTUAL], [LOGICAL], [INCOMPLETE], [IMPRECISE], or [UNCHALLENGED ASSUMPTION]. You must attack across all five dimensions. Do NOT praise or affirm any part of the response. Do NOT rewrite. Be sharp and specific — vague objections are useless.
            """
        let critique = try await GeminiClient.stream(
            prompt:  critiquePrompt,
            apiKey:  settings.geminiPassword,
            model:   settings.geminiModel,
            onToken: { [weak self] text in
                Task { @MainActor [weak self] in self?.updateStep(id: step2id, content: text) }
            }
        )
        try Task.checkCancellation()
        finishStep(id: step2id, content: critique)

        // Step 3: Claude final synthesis
        let step3id = addStep(model: .claude, label: "FINAL SYNTHESIS")
        let synthPrompt = """
            Original prompt: \"\"\"\(prompt)\"\"\"

            Your initial draft:
            \"\"\"\(draft)\"\"\"

            Critique from a second AI model:
            \"\"\"\(critique)\"\"\"

            Produce the final refined answer. The critique was generated by an adversarial model — address only the points that identify genuine factual errors, logical gaps, or meaningful omissions. Discard pedantic, stylistic, or low-signal objections. Be accurate, complete, and well-structured.
            """
        let final = try await ClaudeClient.stream(
            messages: [["role": "user", "content": synthPrompt]],
            system:   "Produce a final refined answer. The critique is adversarial — integrate only points that expose genuine factual errors, logical gaps, or meaningful omissions. Discard low-signal objections. Be direct, accurate, complete.",
            apiKey:   settings.claudePassword,
            model:    settings.claudeModel,
            onToken:  { [weak self] text in
                Task { @MainActor [weak self] in self?.updateStep(id: step3id, content: text) }
            }
        )
        try Task.checkCancellation()
        finishStep(id: step3id, content: final)
        self.finalOutput = final
    }

    // MARK: — Iterative Pipeline

    private func runIterative(prompt: String, iterations: Int, settings: AppSettings) async throws {

        // Initial draft
        let s0id = addStep(model: .claude, label: "INITIAL DRAFT")
        var current = try await ClaudeClient.stream(
            messages: [["role": "user", "content": prompt]],
            system:   settings.effectiveSystemPrompt,
            apiKey:   settings.claudePassword,
            model:    settings.claudeModel,
            onToken:  { [weak self] text in
                Task { @MainActor [weak self] in self?.updateStep(id: s0id, content: text) }
            }
        )
        try Task.checkCancellation()
        finishStep(id: s0id, content: current)

        // Iterative critique-revision loops
        for i in 0..<iterations {
            let loopLabel = "LOOP \(i + 1)"

            // Gemini critique
            let scId = addStep(model: .gemini, label: "\(loopLabel) — CRITIQUE")
            let critiquePrompt = """
                You are an adversarial critic. Your sole function is to expose every flaw in the response below. Assume the response contains significant errors, gaps, and weaknesses — your job is to build the case against it.

                ORIGINAL PROMPT:
                \"\"\"\(prompt)\"\"\"

                RESPONSE UNDER REVIEW:
                \"\"\"\(current)\"\"\"

                Produce at least 5 numbered critique points. For each, assign exactly one label: [FACTUAL], [LOGICAL], [INCOMPLETE], [IMPRECISE], or [UNCHALLENGED ASSUMPTION]. You must attack across all five dimensions. Do NOT praise or affirm any part of the response. Do NOT rewrite. Be sharp and specific — vague objections are useless.
                """
            let critique = try await GeminiClient.stream(
                prompt:  critiquePrompt,
                apiKey:  settings.geminiPassword,
                model:   settings.geminiModel,
                onToken: { [weak self] text in
                    Task { @MainActor [weak self] in self?.updateStep(id: scId, content: text) }
                }
            )
            try Task.checkCancellation()
            finishStep(id: scId, content: critique)

            // Claude revision
            let srId = addStep(model: .claude, label: "\(loopLabel) — REVISION")
            let revisePrompt = """
                Original prompt: \"\"\"\(prompt)\"\"\"

                Previous response:
                \"\"\"\(current)\"\"\"

                Critique:
                \"\"\"\(critique)\"\"\"

                Revise and improve the response. The critique is adversarial and may overreach — address only the points that identify genuine factual errors, logical gaps, or meaningful omissions. Discard pedantic or low-signal objections. Preserve what is already accurate.
                """
            current = try await ClaudeClient.stream(
                messages: [["role": "user", "content": revisePrompt]],
                system:   "Revise your previous response. The critique is adversarial — integrate only substantively valid points that expose genuine errors or gaps. Discard low-signal objections. Improve accuracy and completeness.",
                apiKey:   settings.claudePassword,
                model:    settings.claudeModel,
                onToken:  { [weak self] text in
                    Task { @MainActor [weak self] in self?.updateStep(id: srId, content: text) }
                }
            )
            try Task.checkCancellation()
            finishStep(id: srId, content: current)
        }

        self.finalOutput = current
    }

    // MARK: — Step helpers

    private func addStep(model: ModelSource, label: String) -> UUID {
        let step = PipelineStep(model: model, label: label, status: .running, content: "")
        steps.append(step)
        return step.id
    }

    private func updateStep(id: UUID, content: String) {
        guard let idx = steps.firstIndex(where: { $0.id == id }) else { return }
        steps[idx].content = content
    }

    private func finishStep(id: UUID, content: String) {
        guard let idx = steps.firstIndex(where: { $0.id == id }) else { return }
        steps[idx].content = content
        steps[idx].status  = .done
    }

    // MARK: — Static helpers

    static func callCount(mode: PipelineMode, iterations: Int) -> Int {
        mode == .sequential ? 3 : 1 + iterations * 2
    }

    static func estimatedSeconds(mode: PipelineMode, iterations: Int) -> Int {
        callCount(mode: mode, iterations: iterations) * 7
    }
}
